language: generic

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=2.0.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - sudo curl -L "https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
      - docker-compose -f docker-compose.test.yaml up --build
